### ISSUE TITLE
Getting "npm ERR! notarget No matching version found for forwarded@0.2.0" for npm install command.

### ISSUE THREAD

**Issue by rvmore** [jshttp/forwarded#10]
Hi,

I am getting an anonymous error "npm ERR! notarget No matching version found for forwarded@0.2.0" after doing npm install in the existing project.

Thanks!!

**Comment by dougwilson** [comment]
Typically this happens if you are not using the official registry and there is some issue with your mirror syncing from the official. What is the output of `npm config get registry`?

**Comment by dougwilson** [comment]
Closing due to no response.

**Comment by eldarshmatkov** [comment]
> Typically this happens if you are not using the official registry and there is some issue with your mirror syncing from the official. What is the output of `npm config get registry`?

I`m working through custom .npmrc way, due to security reasons in my company, and my `npm config get registry` is http://10.100.0.137:8082/repository/NPM_0/

**Comment by dougwilson** [comment]
Hi @eldarshmatkov there is nothing wrong with using a different registry, it just means that that registry is out of sync with the npm registry, which is the only one I can publish to. You need to contact whoever manages the registry you are using to correct the problem.
