### ISSUE TITLE
Potential security vulnerability

### ISSUE THREAD

**Issue by ranjit-git** [jshttp/forwarded#11]
A potential security vulnerability has been disclosed for this repo https://huntr.dev/bounties/2b78b547-a92b-47fa-880f-14d176a96220/ 3 months ago .
But i see it still not addressed .
Kindly validate the bug

**Comment by dougwilson** [comment]
Hi @ranjit-git thank you for that link. I'm not sure what that site is, but I was surely never notified about it. I clicked on the link and it just says "This report is not public", even though I signed in. Please provide the details of your protentional issue over to me via email so I can take a look, thank you. You can find my email here: https://github.com/jshttp/forwarded/blob/master/package.json#L6

**Comment by dougwilson** [comment]
Hi @ranjit-git I'm not sure what changed, but I can access it now, thank you.

**Comment by ranjit-git** [comment]
https://huntr.dev site is a opensource bugbounty platform. 
Review the vulnerability details and feel free to mark the report as valid if it's consider to be valid
