### ISSUE TITLE
Support RFC 7239 Forwarded header?

### ISSUE THREAD

**Issue by jstewmon** [jshttp/forwarded#7]
I've always used the de-facto standard X-Forwarded headers, and only recently noticed there is a standard [Forwarded] header.

I was wondering if you'd be interested in supporting it in this package?

If I read the spec correctly, `forwarded-pair` uses the same syntax as `av-pair` from the cookie spec, which led me to try making a parser leveraging the `cookie` package:

```js
const cookie = require("cookie");
const split = require("split-string");

const inputs = [
  `for="_gazona"`,
  `For="[2001:db8:cafe::17]:4711"`,
  `for=192.0.2.60;proto=http;by=203.0.113.43`,
  `for=192.0.2.43, for=198.51.100.17`
];
const parsed = inputs.map(header => {
  const entries = split(header, { quotes: ['"'], separator: "," });
  return entries.map(entry => {
      const parsed = cookie.parse(entry);
      const result = {
          for: undefined,
          by: undefined,
          proto: undefined,
          host: undefined,
      }
      for (const key of Object.keys(parsed)) {
          result[key.toLowerCase()] = parsed[key];
      }
      return result;
  });
});
parsed.forEach(p => console.log('%j', p));
```

```json
[{"for":"_gazona"}]
[{"for":"[2001:db8:cafe::17]:4711"}]
[{"for":"192.0.2.60","by":"203.0.113.43","proto":"http"}]
[{"for":"192.0.2.43"},{"for":"198.51.100.17"}]
```

It seems to work correctly.

But, having a dependency on `cookie` for parsing `forwarded` is awkward...

I wondered if there's an opportunity to create a smaller building block like `httpHeaderPair` that could be used here (or in a separate package)?

[Forwarded]: https://tools.ietf.org/html/rfc7239#section-4

**Comment by ryhinchey** [comment]
@jstewmon I'm not sure if supporting RFC 7239 will be in scope for this package but there's another package that's specifically for parsing the `Forwarded` header: https://github.com/lpinca/forwarded-parse

**Comment by dougwilson** [comment]
Just closing a stale issue.
